language: node_js

node_js:
- '6'

addons:
  apt:
    sources:
    - heroku
    packages:
    - heroku-toolbelt
        
install:
- npm install

script: true

before_deploy:
- cat .netrc >> $HOME/.netrc
- chmod 0600 /home/travis/.netrc
- heroku apps
- heroku apps | grep -q werbk-$TRAVIS_BRANCH || heroku apps:create werbk-$TRAVIS_BRANCH
- heroku git:remote -a werbk-$TRAVIS_BRANCH

deploy:
  provider: heroku
  api_key: fad39043-835a-4ca3-9829-fdb61e4b0be5
  app: werbk-$TRAVIS_BRANCH
  on: $TRAVIS_BRANCH

after_deploy:
- ./node_modules/.bin/wdio wdio.conf || travis_terminate 1
